FORMAT: 1A

# Ezlawyer

Ezlawyer é uma plataforma que permite gesta da contratação de 
correspondentes jurídicos.

# Group Fluxo de integração

Descrever o fluxo necessário para integrar uma Task

# Status das transações

Descrever das trasações de uma Task

# Interpretrando status retornados pela API

Descrever os status retornados na API

# Group Autenticação

Informações necessárioas para a autenticação da API.

## Obtendo o Token de autenticação [/oauth2/token/]

+ Attributes (array[Authentication])

### Gerando o Token [POST]

Para consumir os endpoints fornecidos pela Ezlawyer é necessário informar no 
cabeçalho de cada requisição o token obtido. 

+ Request (application/json)

    + Attributes (array[Authentication])
        
    + Body
    
            {
                "grant_type": "client_credentials",
                "client_id": "<CLIENT_ID>",
                "client_secret": "<CLIENT_SECRET>"
            }
        
+ Response 200 (application/json)

    + Body
    
            {
                "access_token": "<TOKEN>",
                "expires_in": 36000,
                "token_type": "Bearer",
                "scope": "read write groups"
            }


# Group Comarcas

## Pesquisando comarcas disponíveis [/court_district/]
Buscar dados de comarcas cadastradas na base de dados

### Buscar comarcas [GET /court_ditrict/search={search}&name={name}&state={state}]
+ Parameters

    + search: mg - Busca nos campos de nome da comarca e iniciais do estado em que a comarca está localizada.
    + name: belo - Busca no campo de nome da comarca.
    + state: mg - Busca no campo das iniciais do estado em que a comarca está localizada.

+ Response 201 (application/json)

    + Headers
    
            Authorization: "Bearer <TOKEN>"
        
    + Body

            {
                "count": 4,
                "next": null,
                "previous": null,
                "results": [
                    {
                        "id": 895,
                        "name": "Belo Horizonte",
                        "state": 12
                    },
                    {
                        "id": 896,
                        "name": "Belo Vale",
                        "state": 12
                    },
                    {
                        "id": 924,
                        "name": "Campo Belo",
                        "state": 12
                    },
                    {
                        "id": 1049,
                        "name": "Monte Belo",
                        "state": 12
                    }
                ]
            }


# Group Instâncias

## Mantendo o cadastro de instâncias [/instance/]

+ Attributes (array[Instance])

### Criar uma instância [POST]
Cria uma instância e faz o seu vínculo no escritório da sessão de acordo com os dados informados.

+ Request (application/json)

    + Attributes (array[Instance])
    
    + Headers
            
            Authorization: "Bearer <TOKEN>"
    + Body
    
            {
                "name": "1 Instância Judicial"
            }

+ Response 201 (application/json)
    
    + Body
    
            {
                "id": 37,
                "name": "1 Instância Judicial",
                "legacy_code": null
            }

### Listando instâncias [GET /instance/{id}/]
Lista as instâncias cadastradas para o escritório da Sessão.
Caso seja informado o identificador, busca os dados de uma instância específica

+ Parameters

    + id: 37 (number, optional) - Identificador único da instância.

+ Response 201 (application/json)

    + Headers
    
            Authorization: "Bearer <TOKEN>"
        
    + Body
            
            {
                "count": 3,
                "next": null,
                "previous": null,
                "results": [
                    {
                        "id": 39,
                        "name": "3 Instância Judicial",
                        "legacy_code": null
                    },
                    {
                        "id": 38,
                        "name": "2 Instância Judicial",
                        "legacy_code": null
                    },
                    {
                        "id": 37,
                        "name": "1 Instância Judicial",
                        "legacy_code": null
                    }
                ]
            }

### Alterando instância [PUT /instance/{id}]
Altera o cadastro de uma instância específica, de acordo com o id informado.

+ Parameters

    + id: 37 (number, required) - Identificador único da instância.
    
+ Request (application/json)
    
    + Headers
    
            Authorization: "Bearer <TOKEN>"

    + Body

            {
                "name": "01 Instância Judicial",
                "legacy_code": "codigo_legado"
            }
            

+ Response 201 (application/json)
    
    + Body
    
            {
                "id": 37,
                "name": "01 Instância Judicial",
                "legacy_code": "codigo_legado"
            }

### Apagando instância [DELETE /instance/{id}/]
Apaga a instância de acordo com o id informado.

+ Parameters

    + id: 40 (number, required) - Identificador único da instância.

+ Response 204 (application/json)
    + Headers
    
            Authorization: "Bearer <TOKEN>"

### Buscar instancias [GET /instance/search={search}&name={name}&legacy_code={legacy_code}]
Buscar dados de instâncias cadastradas na base de dados
+ Parameters

    + search: judicial - Busca nos campos de nome e legacy_code da instância.
    + name: judicial - Busca no campo de nome da instância.
    + `legacy_code`: codigo_legado - Busca no campo legacy_code da instância, pesquisa por valores exatos.

+ Response 201 (application/json)

    + Headers
    
            Authorization: "Bearer <TOKEN>"
        
    + Body
    
            {
                "count": 1,
                "next": null,
                "previous": null,
                "results": [
                    {
                        "id": 37,
                        "name": "01 Instância Judicial",
                        "legacy_code": "codigo_legado"
                    }
                ]
            }

# Group Órgãos

## Mantendo o cadastro de órgãos [/organ/]

+ Attributes (array[Organ])

### Criar uma instância [POST]
Cria um órgão e faz o seu vínculo no escritório da sessão de acordo com os dados informados.

+ Request (application/json)

    + Attributes (array[Organ])
    
    + Headers
            
            Authorization: "Bearer <TOKEN>"
    + Body
    
            {
                "legal_name": "Fórum de Belo Horizonte",
                "court_district": 895
            }

+ Response 201 (application/json)
    
    + Body
    
            {
                "id": 12193,
                "legal_name": "Fórum de Belo Horizonte 2",
                "name": null,
                "cpf_cnpj": null,
                "court_district": 895,
                "is_active": true,
                "legacy_code": null
            }

### Listando órgãos [GET /organ/{id}/]
Lista os órgãos cadastrados para o escritório da Sessão.
Caso seja informado o identificador, busca os dados de um órgão específico

+ Parameters

    + id: 12193 (number, optional) - Identificador único do órgão.

+ Response 201 (application/json)

    + Headers
    
            Authorization: "Bearer <TOKEN>"
        
    + Body
            
            {
                "count": 3,
                "next": null,
                "previous": null,
                "results": [
                    {
                        "id": 12193,
                        "legal_name": "Fórum de Belo Horizonte",
                        "name": null,
                        "cpf_cnpj": null,
                        "court_district": 895,
                        "is_active": true,
                        "legacy_code": null
                    },
                    {
                        "id": 12194,
                        "legal_name": "Fórum de Belo Horizonte 2",
                        "name": null,
                        "cpf_cnpj": null,
                        "court_district": 895,
                        "is_active": true,
                        "legacy_code": null
                    },
                    {
                        "id": 12192,
                        "legal_name": "Fórum de Contagem",
                        "name": null,
                        "cpf_cnpj": null,
                        "court_district": 952,
                        "is_active": true,
                        "legacy_code": null
                    }
                ]
            }

### Alterando órgão [PUT /organ/{id}]
Altera o cadastro de um órgão específico, de acordo com o id informado.

+ Parameters

    + id: 12194 (number, required) - Identificador único do órgão.
    
+ Request (application/json)
    
    + Headers
    
            Authorization: "Bearer <TOKEN>"

    + Body

            {
                "legal_name": "Fórum de Belo Horizonte 200",
                "court_district": 895,
                "legacy_code": "codigo_legado"
            }
            

+ Response 201 (application/json)
    
    + Body
    
            {
                "id": 12194,
                "legal_name": "Fórum de Belo Horizonte 200",
                "name": null,
                "cpf_cnpj": null,
                "court_district": 895,
                "is_active": true,
                "legacy_code": "codigo_legado"
            }

### Apagando órgão [DELETE /organ/{id}/]
Apaga o órgão de acordo com o id informado.

+ Parameters

    + id: 12194 (number, required) - Identificador único do órgão.

+ Response 204 (application/json)
    + Headers
    
            Authorization: "Bearer <TOKEN>"

### Buscar instancias [GET /organ/search={search}]
Buscar dados de órgãos cadastrados na base de dados
+ Parameters

    + search: Belo Horizonte - Busca nos campos legal_name e legacy_code do órgão, ou pelas iniciais ou nome da comarca em que o órgão está vinculado.

+ Response 201 (application/json)

    + Headers
    
            Authorization: "Bearer <TOKEN>"
        
    + Body
    
            {
                "count": 1,
                "next": null,
                "previous": null,
                "results": [
                    {
                        "id": 37,
                        "name": "01 Instância Judicial",
                        "legacy_code": "codigo_legado"
                    }
                ]
            }

# Group Pessoas

## Mantendo o cadastro de pessoas [/person/]

+ Attributes (array[Person])

### Criar uma pessoa [POST]
Cria uma pessoa e faz o seu vínculo no escritório da sessão, de acordo com os dados informados.
    
+ Request (application/json)

    + Attributes (array[Person])
    
    + Headers
    
            Authorization: "Bearer <TOKEN>"

    + Body

            {
                "legal_name": "Alvo Dumbledore"
            }
            

+ Response 201 (application/json)
    
    + Body
    
            {
                "id": 11380,
                "name": null,
                "legal_name": "Alvo Dumbledore",
                "legal_type": "J",
                "cpf_cnpj": null,
                "is_lawyer": false,
                "is_customer": false,
                "is_supplier": false,
                "is_active": true,
                "legacy_code": null
            }

### Listando pessoas [GET /person/{id}/]
Lista as pessoas cadastradas para o escritório da Sessão.
Caso seja informado o identificador, busca os dados de uma pessoa específica

+ Parameters

    + id: 11380 (number, optional) - Identificador único da pessoa.

+ Response 201 (application/json)

    + Headers
    
            Authorization: "Bearer <TOKEN>"
        
    + Body

            {
                "count": 3,
                "next": null,
                "previous": null,
                "results": [
                    {
                        "id": 11380,
                        "name": null,
                        "legal_name": "Alvo Dumbledore",
                        "legal_type": "J",
                        "cpf_cnpj": null,
                        "is_lawyer": false,
                        "is_customer": false,
                        "is_supplier": false,
                        "is_active": true,
                        "legacy_code": null
                    },
                    {
                        "id": 11382,
                        "name": null,
                        "legal_name": "Arthur Dent",
                        "legal_type": "F",
                        "cpf_cnpj": "47704895010",
                        "is_lawyer": false,
                        "is_customer": false,
                        "is_supplier": false,
                        "is_active": true,
                        "legacy_code": null
                    },
                    {
                        "id": 11381,
                        "name": null,
                        "legal_name": "Severo Snape",
                        "legal_type": "F",
                        "cpf_cnpj": null,
                        "is_lawyer": false,
                        "is_customer": false,
                        "is_supplier": false,
                        "is_active": true,
                        "legacy_code": null
                    }
                ]
            }

### Alterando pessoas [PUT /person/{id}]
Altera o cadastro de uma pessoa específica, de acordo com o id informado.

+ Parameters

    + id: 11381 (number, required) - Identificador único da pessoa.
    
+ Request (application/json)
    
    + Headers
    
            Authorization: "Bearer <TOKEN>"

    + Body

            {
                "legal_name": "Severo Snape",
                "is_lawyer": true
            }
            

+ Response 201 (application/json)
    
    + Body
    
            {
                "id": 11381,
                "name": null,
                "legal_name": "Severo Snape",
                "legal_type": "F",
                "cpf_cnpj": null,
                "is_lawyer": true,
                "is_customer": false,
                "is_supplier": false,
                "is_active": true,
                "legacy_code": null
            }

### Apagando pessoa [DELETE /person/{id}/]
Apaga a pessoa de acordo com o id informado.

+ Parameters

    + id: 11382 (number, required) - Identificador único da pessoa.

+ Response 204 (application/json)
    + Headers
    
            Authorization: "Bearer <TOKEN>" 

# Group Pastas

## Mantendo o cadastro de pastas [/folder/]

+ Attributes (array[Folder])

### Criar uma pasta [POST]
Cria uma pasta vinculada ao escritório da sessão de acordo com os dados informados

+ Request (application/json)
    
    + Headers
    
            Authorization: "Bearer <TOKEN>",
        
    + Body
        
            {
                "person_customer": 11384,
                "cost_center": null,
                "legacy_code": ""
            }
    
+ Response 201 (application/json)
    
    + Body
    
            {
                "id": 21237,
                "folder_number": 1,
                "person_customer": 11384,
                "cost_center": null,
                "legacy_code": ""
            }

### Listando pastas [GET /folder/{id}]
Listar Pastas cadastradas para o escritíorio da sessão. 
Caso seja informado um identificador será listado apenas a pasta selecionado.

+ Parameters

    + id: 1 (number, optional) - Identificador único da pasta.

+ Response 201 (application/json)
    + Headers
    
            Authorization: "Bearer <TOKEN>" 
        
    + Body
        
            {
                "count": 2,
                "next": null,
                "previous": null,
                "results": [
                    {
                        "id": 21238,
                        "folder_number": 2,
                        "person_customer": 11384,
                        "cost_center": null,
                        "legacy_code": ""
                    },
                    {
                        "id": 21237,
                        "folder_number": 1,
                        "person_customer": 11384,
                        "cost_center": null,
                        "legacy_code": ""
                    }
                ]
            }
        

### Alterando pasta [PUT /folder/{id}]
Alterar a pasta de acordo com o ID informado

+ Parameters

    + id: 21238 (number, required) - Identificador único da pasta.

+ Request (application/json)
    
    + Headers
    
            Authorization: "Bearer <TOKEN>"

    + Body

            {
                "person_customer": 11384,
                "cost_center": null,
                "legacy_code": "Vogons01"
            }

+ Response 200 (application/json)
    + Headers
    
            Authorization: "Bearer <TOKEN>" 
        
    + Body
        
            {
                "id": 21238,
                "folder_number": 0,
                "person_customer": 11384,
                "cost_center": null,
                "legacy_code": "Vogons01"
            }

### Apagando pasta [DELETE /folder/{id}/]
Apaga a pasta de acordo com o Id informado.

+ Parameters

    + id: 1 (number, required) - Identificador único da pasta.

+ Response 201 (application/json)
    + Headers
    
            Authorization: "Bearer <TOKEN>" 
        
    + Body
    
            {
            }

# Group Processos

## Mantendo o cadastro de processos [/lawsuit/]

+ Attributes (array[LawSuit])

### Criar um processo [POST]
Cria um processo no escritório da sessão

+ Request (application/json)
    
    + Headers
    
            Authorization: "Bearer <TOKEN>",
        
    + Body
        
            {
                "person_customer": 11194,
                "cost_center":
                "legacy_code":
            }

### Listando processos [GET /lawsuit/{id}]
Lista Processos cadastradas para o escritíorio da sessão. 
Caso seja informado um identificador será listado apenas o processo selecionado.

+ Parameters

    + id: 1 (number, optional) - Identificador único da pasta.

+ Response 201 (application/json)
    + Headers
    
            Authorization: "Bearer <TOKEN>" 
        
    + Body
        
            {
                "count": 1,
                "next": null,
                "previous": null,
                "results": [
                    {
                        "id": 13604,
                        "office": 171,
                        "folder_number": 1,
                        "person_customer": 11194,
                        "cost_center": null,
                        "create_user": 2,
                        "legacy_code": null
                    }
                ]
            }
        

### Alterando processo [PUT /lawsuit/{id}]
Altera o processo de acordo com o ID informado

+ person_customer: `11194` (integer, required) - Identificador do cliente cadastrado no escritório que será vinculado à pasta
+ cost_center: `15` (integer) - Identificador do centro de custo
+ legacy_code: `123456` (string) - Identificador da pasta no sistema legado

+ Parameters

    + id: 1 (number, required) - Identificador único da pasta.

+ Response 200 (application/json)
    + Headers
    
            Authorization: "Bearer <TOKEN>" 
        
    + Body
        
            {
                "id": 13604,
                "folder_number": 1,
                "person_customer": 11194,
                "cost_center": null,
                "legacy_code": null
            }

### Apagando processo [DELETE /lawsuit/{id}/]
Apaga o processo de acordo com o Id informado.

+ Parameters

    + id: 1 (number, required) - Identificador único da pasta.

+ Response 201 (application/json)
    + Headers
    
            Authorization: "Bearer <TOKEN>" 
        
    + Body
    
            {
            }

## Data Structures

### Authentication
+ grant_type: client_credentials (required) - Fixo: client_credentials.
+ client_id: <CLIENT_ID> (required) - Informar o client_id fornecido.
+ client_secret: <CLIENT_SECRET> (required) - Informar o client_secret fornecido.

### Person
+ legal_name: Alvo Dumbledore (required) - Nome da Pessoa ou Razão social
+ name: Alvos Dumbledore - Nome da pessoa ou Nome Fantasia
+ cpf_cnpj: 00000000000 - CPF ou CNPJ (devem ser válidos, caso seja enviado)
+ legal_type: F, J (array, required) - Tipo da pessoa

    + Padrão: J
        
+ is_lawyer: false (boolean) - Esta opção define se a pessoa é um advogado
+ is_costumer: false (boolean) - Esta opção define se a pessoa é um cliente
+ is_supplier: false (boolean) - Esta opção define se a pessoa é um fornecedor
+ is_active: true (boolean) - Esta opção define se a pessoa está ativa

### Folder
+ person_customer: `11384` (number, required) - Identificador do cliente cadastrado no escritório que será vinculado à pasta
+ cost_center: `15` (number) - Identificador do centro de custo
+ legacy_code: `123456` (string) - Identificador da pasta no sistema legado

### LawSuit
+ folder: 15 (number, required) - Id da pasta a ser vinculada com o processo
+ law_suit_number: `0000000-00.2018.0.00.0000` (string, required) - Número do processo
+ court_district: 952 (number, required) - Id da comarca a ser vinculada com o processo
+ instance: 50 (number, required) - Id da instância a ser vinculada com o processo
+ person_lawyer: 11194 (number) - Identificador do advogado cadastrado no escritório que será vinculado ao processo
+ organ: 0 (number) - Identificador do órgão cadastrado no escritório que será vinculado ao processo
+ court_division: 0 (number) - Identificador da vara cadastrada no escritório que será vinculada ao processo
+ is_current_instance: false (boolean)
+ opposing_party: '' (string) - Especificação da parte adversa do processo
+ legacy_code: `123456` (string) - Identificador do processo no sistema legado

### Instance
+ name: `1 Instância Judicial` (string, required) - Nome da Instância
+ legacy_code: `123456` (string) - Identificador da instância no sistema legado

### Organ
+ legal_name: Fórum Belo Horizonte (required) - Nome do Órgão
+ name: Fórum Belo Horizonte - Nome ou Nome Fantasia do Órgão
+ cpf_cnpj: 00000000000 - CPF ou CNPJ (devem ser válidos, caso seja enviado)
+ court_district: 895 (number, required) - Id da comarca a ser vinculada com o orgão
+ legacy_code: `123456` (string) - Identificador do órgão no sistema legado